common:
  pg_bin_path: "/usr/bin"
  tmp_dir: "/tmp"

log:
  level: "info"

validate:
  data: true
  diff: true
  rows_limit: 2

storage:
  type: "s3"
  s3:
    endpoint: "http://storage:9000"
    bucket: "adventureworks"
    region: "us-east-1"
    access_key_id: "Q3AM3UQ867SPQQA43P2F"
    secret_access_key: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"

dump:
  pg_dump_options:
    dbname: "postgresql://postgres:example@db:5432/postgres"
    jobs: 2

  transformation: # List of tables to transform
    - schema: "public"
      name: "account"
      transformers:
        - name: "RandomInt"
          params:
            column: "id"
            engine: hash
            min: 1
            max: 100

        - name: "RandomChoice"
          params:
            column: "gender"
            values:
              - "M"
              - "F"

        - name: "RandomPerson"
          params:
            columns:
              - name: "first_name"
                template: "{{ .FirstName }}"
              - name: "last_name"
                template: "{{ .LastName }}"
          dynamic_params:
            gender:
              column: gender

        - name: "RandomEmail"
          params:
            column: "email"
            engine: "hash"
            keep_original_domain: true
            keep_null: false
            local_part_template: "{{ first_name | lower }}.{{ last_name | lower }}"

        - name: "RandomDate"
          params:
            column: "birth_date"
            min: '{{ now | tsModify "-30 years" | .EncodeValue }}' # 1994
            max: '{{ now | tsModify "-18 years" | .EncodeValue }}' # 2006

        - name: "RandomDate"
          params:
            column: "created_at"
            max: "{{ now | .EncodeValue }}"
            truncate: "day"
          dynamic_params:
            min:
              column: "birth_date"
              template: '{{ .GetValue | tsModify "18 years" | .EncodeValue }}'

    - schema: "public"
      name: "orders"
      transformers:

        - name: "RandomInt"
          params:
            column: "account_id"
            engine: hash
            min: 1
            max: 100
        #            max: 2147483647

        - name: "NoiseNumeric"
          params:
            column: "total_price"
            decimal: 2
            min_ratio: 0.1
            max_ratio: 0.9

        - name: "NoiseDate"
          params:
            column: "created_at"
            max_ratio: "6 day"
            min_ratio: "1 day"
            truncate: "day"

        - name: "RandomDate"
          params:
            column: "paid_at"
            max: '{{ now | .EncodeValue }}'
            truncate: "day"
          dynamic_params:
            min:
              column: "created_at"

restore:
  pg_restore_options:
    jobs: 10
    dbname: "postgresql://postgres:example@localhost:54316/transformed"
    exit-on-error: true
