version: '3'

services:
  storage:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - "MINIO_ROOT_USER=Q3AM3UQ867SPQQA43P2F"
      - "MINIO_ROOT_PASSWORD=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
    entrypoint: sh
    command: >
      -c 'mkdir -p /export/adventureworks && minio server /export --console-address :9001'
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 10s
      timeout: 5s
      retries: 2

  db:
    volumes:
      - "/var/lib/postgresql/data"
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    image: postgres:16
    ports:
      - "54316:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: [ "CMD", "psql", "-U", "postgres" ]
      interval: 5s
      timeout: 1s
      retries: 3

  greenmask:
    volumes:
      - ./:/var/lib/playground
    image: "greenmask/greenmask:v0.2.0b1"
    working_dir: /var/lib/playground
    environment:
      PGPASSWORD: example
      ORIGINAL_DB_NAME: "original"
      TRANSFORMED_DB_NAME: "transformed"
      DATABASE_HOST: "playground-db"
    depends_on:
      db:
        condition: service_healthy
      storage:
        condition: service_healthy
    entrypoint: bash
